# Generated by Django 5.0 on 2024-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=45)),
                ("creator", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=45)),
                ("description", models.TextField(blank=True, null=True)),
                ("street", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=45)),
                ("state", models.CharField(blank=True, max_length=45)),
                ("location", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True)),
                ("end_date", models.DateField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
