# Generated by Django 5.0 on 2024-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_creator_alter_event_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
