# Generated by Django 5.0 on 2024-01-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_end_date_alter_event_start_date"),
        ("organizations", "0002_alter_organization_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="creator",
        ),
        migrations.AlterField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="organizations.organization",
            ),
        ),
    ]
