# Generated by Django 4.2.3 on 2023-07-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_name',
            new_name='name',
        ),
    ]
