# Generated by Django 4.2.3 on 2023-07-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='user',
            new_name='creator',
        ),
    ]
